# Generated by Django 5.2.7 on 2025-10-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_content_article_article_remove_article_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Wikipedia Researcher + CrewAI Agents', max_length=255),
        ),
    ]
